run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - bodyclose
    - noctx
    - rowserrcheck
    - gosec
    - misspell
    - gocyclo
    - goimports
    - revive
    - unconvert
    - dupl
    - prealloc
    - exportloopref

linters-settings:
  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G404 # Use of weak random number generator - acceptable for non-crypto use

  govet:
    check-shadowing: true

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl

    - path: cmd/
      linters:
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
