version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: recontronic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recontronic
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recontronic

  redis:
    image: redis:7-alpine
    container_name: recontronic-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - recontronic

  api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: recontronic-api
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATABASE_HOST=timescaledb
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=recontronic
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_ENVIRONMENT=development
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - recontronic
    restart: unless-stopped

  worker:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.worker
    container_name: recontronic-worker
    environment:
      - DATABASE_HOST=timescaledb
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=recontronic
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_CONCURRENCY=5
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - recontronic
    restart: unless-stopped

volumes:
  timescale-data:
  redis-data:

networks:
  recontronic:
    driver: bridge
